import argparse
import os
import json
import re
import sys

def validate_mem_files(directory):
    """
    Validate the format and content of .mem files generated by export.py.
    """
    manifest_path = os.path.join(directory, "weights_manifest.json")
    if not os.path.exists(manifest_path):
        print(f"Error: manifest missing at {manifest_path}")
        sys.exit(1)
        
    try:
        with open(manifest_path, 'r') as f:
            manifest = json.load(f)
    except Exception as e:
        print(f"Error reading manifest: {e}")
        sys.exit(1)
        
    # Regex for exactly 2 uppercase hex characters
    hex_regex = re.compile(r"^[0-9A-F]{2}$")
    
    for layer_name, info in manifest.items():
        mem_file = info['mem_file']
        mem_path = os.path.join(directory, mem_file)
        num_values = info['num_values']
        scale = info['scale_factor']
        
        if not os.path.exists(mem_path):
            print(f"Error: {mem_file} missing for layer {layer_name}")
            sys.exit(1)
            
        if not isinstance(scale, (int, float)) or scale <= 0:
            print(f"Error: invalid scale_factor {scale} for layer {layer_name}")
            sys.exit(1)
            
        try:
            with open(mem_path, 'r') as f:
                lines = [l.strip() for l in f.readlines()]
                # Filter out empty lines if any (though export.py shouldn't create them)
                lines = [l for l in lines if l]
        except Exception as e:
            print(f"Error reading {mem_file}: {e}")
            sys.exit(1)
            
        if len(lines) != num_values:
            print(f"Error: {mem_file} has {len(lines)} lines, expected {num_values}")
            sys.exit(1)
            
        for i, line in enumerate(lines):
            if not hex_regex.match(line):
                print(f"Error: {mem_file} line {i+1} has invalid format: '{line}' (expected 2-digit uppercase hex)")
                sys.exit(1)
                
    print("All .mem files valid.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Validate .mem weight files for hardware handoff.")
    parser.add_argument("--dir", required=True, help="Directory containing .mem files")
    args = parser.parse_args()
    validate_mem_files(args.dir)
